### PR TITLE
.NET Core Launch (web)

### PR DESCRIPTION
**Pull request by zandiarash**
why not to have lunch web ?

### CODE REVIEW

**Comment by jakubmisek** [comment]
how is it different from `"name": ".NET Core Launch (console)",`  ?

**Comment by zandiarash** [comment]
I've added this part
```
 "launchBrowser": {
                "enabled": true
            },
```

**Comment by jakubmisek** [comment]
I see, nice!

**Comment by jakubmisek** [comment]
thank you @Arashz22

**Comment by zandiarash** [comment]
thanks for merging

**Pull request merged**
